Feat/add blog rookify
SovereignCloudStack/website pull request #1012
Opened 2024-09-04 11:04 UTC by fkr

2024-09-05 05:14 UTC, fkr commented on _i18n/de/_posts/blog/2024-08-26-ceph-rook.md
> +Da ceph-ansible nun [veraltet](https://github.com/ceph/ceph-ansible/commit/a9d1ec844d24fcc3ddea7c030eff4cd6c414d23d) ist, unterstützt SCS jetzt die Bereitstellung von Ceph mithilfe von [Rook](https:/
```suggestion
Da ceph-ansible nun [veraltet](https://github.com/ceph/ceph-ansible/commit/a9d1ec844d24fcc3ddea7c030eff4cd6c414d23d) ist, unterstützt die SCS Referenzimplementierung jetzt die Bereitstellung von Ceph mithilfe von [Rook](https://rook.io/docs/rook/latest-release/Getting-Started/intro/), einem ["graduated-level cloud-native project"](https://www.cncf.io/announcements/2020/10/07/cloud-native-computing-foundation-announces-rook-graduation/).
```

2024-09-05 05:15 UTC, fkr commented on _i18n/en/_posts/blog/2024-08-26-ceph-rook.md
> +With the [depreceation](https://github.com/ceph/ceph-ansible/commit/a9d1ec844d24fcc3ddea7c030eff4cd6c414d23d) of ceph-ansible, SCS now supports Ceph deployment with [Rook](https://rook.io/docs/rook/l
```suggestion
With the [depreceation](https://github.com/ceph/ceph-ansible/commit/a9d1ec844d24fcc3ddea7c030eff4cd6c414d23d) of ceph-ansible, the SCS reference implementation now supports Ceph deployment with [Rook](https://rook.io/docs/rook/latest-release/Getting-Started/intro/), a [graduated-level cloud-native project](https://www.cncf.io/announcements/2020/10/07/cloud-native-computing-foundation-announces-rook-graduation/).
```

2024-09-05 05:17 UTC, fkr commented on _i18n/de/_posts/blog/2024-08-27-rookify.md
> +Neue Funktionen sind in Entwicklung, welche die bestehende CLI-Oberfläche verbessern. Das cli sollte die Pickle-Datei lesen und die Module von Rookify verwenden können, um den genauen Stand des Migra
```suggestion
Neue Funktionen sind in Entwicklung, welche die bestehende CLI-Oberfläche verbessern. Das CLI sollte die Pickle-Datei lesen und die Module von Rookify verwenden können, um den genauen Stand des Migrationsprozesses zu berichten. Das bedeutet, dass Rookify genau dort fortfahren kann, wo eine unterbrochene oder teilweise fehlgeschlagene Migration aufgehört hat.
```

2024-09-05 05:17 UTC, fkr commented on _i18n/de/_posts/blog/2024-08-27-rookify.md
> +## Testlauf: Ausprobierne und beim Testen helfen
```suggestion
## Testlauf: Ausprobieren und beim Testen helfen
```

2024-09-05 05:19 UTC, fkr reviewed
@boekhorstb1 Very cool articles.
Couple suggestions:

1) Let's move these into two PRs: one for the rook posts, one for the rookify posts
2) Update the dates (for example tomorrow and monday)
3) Let's get someone else to give it a final review, but they do LGTM.

2024-09-25 08:15 UTC, boekhorstb1 commented
ok @fkr I moved this into two prs. The rook pr is found here https://github.com/SovereignCloudStack/website/pull/1026

2024-09-25 08:16 UTC, boekhorstb1 commented
@NotTheEvilOne I added you as reviewer, as Felix suggested to have one more approval :)

2024-10-08 09:03 UTC, boekhorstb1 commented
ok we made some significant changes to rook and as we did not pull this PR yet, I will try to incorporate them now

2024-10-08 10:28 UTC, boekhorstb1 commented
ok latest changes should now be included in both the english and german version.

If we like, we can also wait for the osism/scs docs of rookify to be published. We could then mention them in this post as well. See [here](https://github.com/osism/osism.github.io/pull/688).

2024-10-23 19:13 UTC, NotTheEvilOne requested changes

2024-10-23 19:13 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +2. Nun werden die ausgeschalteten Instanzen Rook zur Wiederherstellung übergeben.
2. Von den verbliebenen zwei Instanzen wird nun die erste ebenfalls abgeschaltet aber anschließend in Rook zum Scheduling freigegeben, sodass eine Rook-Instanz startet. Auf diesen Start wird gewartet, bevor die zweite (verbliebene) Instanz abgeschaltet und in Rook aktiviert wird. Alle weiteren Instanzen werden anschließend in Rook abgebildet.

2024-10-23 19:13 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +Wenn Sie den aktuellen Stand von Rookify testen möchten (sehr geschätzt - melden Sie gerne [issues](https://github.com/SovereignCloudStack/rookify/issues) bei Github), können Sie das Testbed von OSIS
nit: ... melden Sie gerne [Issues](https://github.com/SovereignCloudStack/rookify/issues) bei ...

2024-10-23 19:13 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +Führen Sie `make setup` aus, damit automatisch das Rookify-Repository gekloned und aufgesetzt wird: es erstellt automatisch eine virtuelle Python-Umgebung, lädt die nötigen Python-Bybliotheken herunt
... indem Sie einfach `make` (das gleiche wie `make help`) **im** Stammverzeichnis ...

2024-10-23 19:13 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> + Wenn Sie einen Fehler über das Fehlen der python-rados-Bibliothek erhalten, können Sie `make check-radoslib` ausführen, um zu prüfen, ob die Bibliothek lokal installiert ist. Wenn nicht, installiere
... das Fehlen der `python-rados`-Bibliothek erhalten ...

2024-10-23 19:13 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +Stellen Sie sicher, dass Rookify eine Verbindung zum Testbett herstellen kann. Weitere Informationen zum Einrichten einer VPN-Verbindung finden Sie in der [OSISM-Dokumentation](https://osism.tech/doc
... zum **Testbed** herstellen ...

2024-10-23 19:13 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +Jetzt können Sie endlich Rookify ausführen, um es zu testen. Rookify erlaubt die Verwendung von `--dry-run`, um Module im Preflight-Modus auszuführen. Beachten Sie, dass Rookify die verschiedenen Mod
nit: ... ausführen um es zu testen.

alternative:
Beachten Sie, dass Rookify die verschiedenen Module immer zuerst im Preflight-Modus ausführt bevor anschließend, bei fehlerfreiem Durchlauf, eine Migration gestartet wird.

2024-10-23 19:13 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +Wenn alles korrekt eingerichtet ist, können Sie Rookify ohne Argumente ausführen oder sie wagen es explizit `--migrate` als Argument zu geben. In diesem Fall machen Sie nichts kaput, wenn Sie das `an
... `analyze_ceph`-Modul ausführen, da ...

2024-10-23 19:13 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +Wir können Rookify zunächst mit `pre-flight` starten, um zu prüfen, ob alles in Ordnung ist, und es dann explizit mit dem Argumente `--migrate` versehen, um die wirkliche Migration zu starten. Als Er
nit: ... ob alles in Ordnung ist und es ...
typo: ... mit dem Argument ...

2024-10-23 19:13 UTC, NotTheEvilOne commented on _i18n/en/_posts/blog/2024-10-08-rookify.md
> +The `-s` or `--show-states` has been added to track the state of progress. If you added a pickle file to the setup, this file will be taken into account as well: each separate module will check the c
Please integrate the changes noted in the German variant.

2024-10-23 19:13 UTC, NotTheEvilOne commented on _i18n/en/_posts/blog/2024-10-08-rookify.md
> +1. all OSD daemons have to switched of at once
Please integrate the changes noted in the German variant.

2024-10-23 19:13 UTC, NotTheEvilOne commented on _i18n/en/_posts/blog/2024-10-08-rookify.md
> +1. 2 mds instances (at least one has to be active) will be left under Ceph-Ansible, all others will be switched off. For example, in case of a total of 3 mds instances, only one mds instance will be
Please integrate the changes noted in the German variant.

2024-10-24 08:22 UTC, boekhorstb1 commented
Thanks @NotTheEvilOne :)

2024-10-24 08:51 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +Rookify kann durch Bearbeiten einer umfassenden `config.yml`-Datei konfiguriert werden, wie zum Beispiel in der bereitgestellten [config.example.yaml](https://github.com/SovereignCloudStack/rookify/b
nit: `config.yaml` instead of `.yml`

Please replace subsequent uses as well.

2024-10-24 08:51 UTC, NotTheEvilOne commented on _i18n/en/_posts/blog/2024-10-08-rookify.md
> +Rookify can be configured by editing a comprehensive `config.yml` file, such as the provided [confing.example.yaml](https://github.com/SovereignCloudStack/rookify/blob/main/config.example.yaml). This
nit: `config.yaml` instead of `.yml`

Please replace subsequent uses as well.

2024-10-24 08:51 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +1. Preflight-Modus: Das `migrate_mons` Modul läuft zuerst im Preflight-Modus, der auch manuell mit dem Befehl `rookify --dry-run` ausgelöst werden kann. In dieser Phase, führt Rookify die Preflight-M
nit: ... In dieser Phase führt ...

2024-10-24 08:51 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +    1. `analyze_ceph` Modul: Rookify erkennt, dass das `analyze_ceph` Modul in jedem Fall zuerst ausgeführt werden muss. Das `analyze_ceph` Modul sammelt Daten über die laufenden Ceph-Ressourcen und
nit: ... Beachten Sie, dass `analyze_ceph` zuerst, wie bei jedem anderen Modul, im Preflight-Modus läuft. Es wird geprüft, ob der ...

2024-10-24 08:51 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +    2. Cluster-Erstellung: Nach erfolgreicher Ausführung des `analyze_ceph` Moduls überprüft Rookify auf weitere Abhängigkeiten, wie das `create_rook_cluster` Modul. Dieses Modul erstellt die `cluste
nit: ... auf weitere Abhängigkeiten wie das ...

Additionally validating for k8s namespace is done in `k8s_prerequisites_check` and it is required that the cluster namespace has been created manually. Only the `CephCluster` resource is generated in `create_rook_cluster`.

2024-10-24 08:51 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +Wenn wir jetzt in das Testbed einloggen können wir die "Health" des clusters nochmal mit `ceph -s` kontrollieren. Mit `kubectl` kann man noch checken, das alles pods da sind.
nit: ... alle Pods da sind.

2024-10-24 09:30 UTC, boekhorstb1 commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +    2. Cluster-Erstellung: Nach erfolgreicher Ausführung des `analyze_ceph` Moduls überprüft Rookify auf weitere Abhängigkeiten, wie das `create_rook_cluster` Modul. Dieses Modul erstellt die `cluste
ok, I added information about the `k8s_prerequisites_check` as well

2024-10-24 10:31 UTC, NotTheEvilOne approved these changes
Beside two small additional changes it looks good for me :)

2024-10-24 10:31 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +Wenn wir jetzt in das Testbed einloggen können wir die "Health" des clusters nochmal mit `ceph -s` kontrollieren. Mit `kubectl` kann man noch checken, das alles Pods da sind.
nit: ... das alle Pods da sind.

2024-10-24 10:31 UTC, NotTheEvilOne commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +Kopieren Sie `config.example.osism.yml` nach `config.yaml`und ändern Sie die verschiedenen Konfigurationseinstellungen nach Bedarf. Rookify benötigt Zugriff auf einen SSH-Schlüssel (z.B. die `.id_rsa
nit: `config.example.osism.yaml` (in English as well)

2024-10-24 11:23 UTC, boekhorstb1 commented on _i18n/de/_posts/blog/2024-10-08-rookify.md
> +Kopieren Sie `config.example.osism.yml` nach `config.yaml`und ändern Sie die verschiedenen Konfigurationseinstellungen nach Bedarf. Rookify benötigt Zugriff auf einen SSH-Schlüssel (z.B. die `.id_rsa
ups thanks :)

2024-10-24 11:41 UTC, boekhorstb1 commented
@fkr I think you can merge :)

2024-10-25 16:59 UTC, garloff commented
Somebody should hit the "Squash and merge" button, no?
Any reason for not doing so, @boekhorstb1, @NotTheEvilOne, @fkr?

2024-10-30 08:58 UTC, merged

2024-10-30 08:58 UTC, boekhorstb1 commented
ok I merged it :)