Feat/add blog rook only
SovereignCloudStack/website pull request #1026
Opened 2024-09-25 08:13 UTC by boekhorstb1

separated rook greenfield blog in this separate PR as suggested by @fkr

2024-09-25 08:18 UTC, boekhorstb1 commented
@b1-lender I added you as reviewer beacuse Felix suggested to have one more review and approval

2024-10-07 09:16 UTC, b1-lender requested changes
Other that that, it's fine.

2024-10-08 08:20 UTC, b1-lender approved these changes

2024-10-14 20:54 UTC, fkr approved these changes

2024-10-14 20:57 UTC, merged