SCS Wallaby Update Experience
SovereignCloudStack/website pull request #233
Opened 2022-02-01 08:49 UTC by matfechner

Signed-off-by: Mathias Fechner <mathias.fechner@plusserver.com>

some little post for the  Rabbitmq User Story

2022-02-01 08:50 UTC, matfechner commented
Hi  @itrich here is  my post

2022-02-01 12:28 UTC, garloff commented on _i18n/en/_posts/blog/2022-02-01-wallaby-upgrade.md
> +Since more then one year Plusserver has provided the SCS Community Community Environment.
double Community

2022-02-01 12:29 UTC, garloff commented on _i18n/en/_posts/blog/2022-02-01-wallaby-upgrade.md
> +One cosmetic issue was, that the neutron-metadata-agent was missing in "openstack network agent list"
no comma in English

2022-02-01 12:31 UTC, garloff commented on _i18n/en/_posts/blog/2022-02-01-wallaby-upgrade.md
> +After an intensive diagnostic session we decided to roll rabbitmq back to the victoria container image version,
Would it be good to mention the rabbitmq version numbers included in the Victoria and Wallaby containers?

2022-02-01 12:31 UTC, garloff commented on _i18n/en/_posts/blog/2022-02-01-wallaby-upgrade.md
> +We have filed an issue against the osism testbed in order to see, when the bug is fixed (https://github.com/osism/testbed/issues/978).
Do we have further plans beyond reporting? E.g. working with the upstream community to deploy potential fixes and validate whether they work?

2022-02-01 12:43 UTC, fkr commented on _i18n/en/_posts/blog/2022-02-01-wallaby-upgrade.md
> +After an intensive diagnostic session we decided to roll rabbitmq back to the victoria container image version,
@garloff makes sense to include those imho

2022-02-01 13:38 UTC, garloff commented on _i18n/en/_posts/blog/2022-02-01-wallaby-upgrade.md
> +We have filed an issue against the osism testbed in order to see, when the bug is fixed (https://github.com/osism/testbed/issues/978).
Taking this one step further: This should hit all Wallaby kolla-ansible deployments, no?

2022-02-01 15:09 UTC, matfechner commented on _i18n/en/_posts/blog/2022-02-01-wallaby-upgrade.md
> +We have filed an issue against the osism testbed in order to see, when the bug is fixed (https://github.com/osism/testbed/issues/978).
@garloff, @fkr   that is necessary to prove, but in long term running osism testbed with wallaby, we have not noticed.  The rabbitmq in the last stable versions is still fixed.  i will continue the Markdown with the planned update procedure for the rabbitmq cluster, Thank you for feedback

2022-02-01 18:33 UTC, itrich requested changes

2022-02-16 13:00 UTC, matfechner commented
Hi @itrich, i hope now  it is looking better  https://github.com/SovereignCloudStack/website/pull/233/commits/545894ae837d05bd179f1a1174df5a2db87a41ca

2022-02-16 13:39 UTC, itrich approved these changes

2022-02-16 13:39 UTC, merged