feat/add ansible lint quality post osism
SovereignCloudStack/website pull request #347
Opened 2022-07-14 09:02 UTC by ra-rau

- add boilerplate for the ansibe linting blog post by @ra-rau
- oops. There is no Rautenbach.
- Add Content for the Blogpost

2022-07-14 12:00 UTC, itrich requested changes

2022-07-14 13:03 UTC, fkr commented on _i18n/en/_posts/blog/2022-07-14-osism-ansible-lint-quality.md
> +image: "XXX"
that marker was from me, since I wasn't sure what kind of image we would use.

2022-07-14 13:11 UTC, itrich commented on _i18n/en/_posts/blog/2022-07-14-osism-ansible-lint-quality.md
> +image: "XXX"
What about this image?
https://www.pexels.com/photo/corrections-on-a-paragraph-written-on-a-paper-beside-crumpled-paper-5185079/

2022-07-14 13:15 UTC, fkr commented on _i18n/en/_posts/blog/2022-07-14-osism-ansible-lint-quality.md
> +image: "XXX"
like that. @ra-rau fine with you?

2022-07-15 05:33 UTC, ra-rau commented on _i18n/en/_posts/blog/2022-07-14-osism-ansible-lint-quality.md
> +image: "XXX"
Do we need an image?

2022-07-15 05:49 UTC, itrich commented on _i18n/en/_posts/blog/2022-07-14-osism-ansible-lint-quality.md
> +image: "XXX"
You don't need to provide an image. The image is used for the background on the carousel at <scs.community> and for social media sharing. If no image is provided, the template will fall back to the default image (the pier with view on the open sea). It's your blogpost – you decide :smile:

2022-07-15 05:56 UTC, ra-rau commented on _i18n/en/_posts/blog/2022-07-14-osism-ansible-lint-quality.md
> +image: "XXX"
Take the image what you have found, i am fine with that. 😄

2022-07-15 05:56 UTC, ra-rau commented on _i18n/en/_posts/blog/2022-07-14-osism-ansible-lint-quality.md
> +For more information on Ansible Lint and its functionality, please look at the documentation: https://ansible-lint.readthedocs.io/en/latest/.
Done

2022-07-15 05:57 UTC, ra-rau commented on _i18n/en/_posts/blog/2022-07-14-osism-ansible-lint-quality.md
> +For many, the topic of Ansible FQCN is still very controversial and unnecessary (https://github.com/ansible/ansible-lint/issues/2050). We have decided that we will implement it, because we think the
Done

2022-07-15 06:20 UTC, itrich commented
I added the image as discussed. Furthermore I added a style definition for `pygments` (the syntax highlightning engine by Jekyll – we hadn't one yet). I decided to go with `zenburn`: http://jwarby.github.io/jekyll-pygments-themes/languages/java.html 
Hope you like it :smiley: 

The posting LGTM now. Thank you so much for contributing! :heart:

2022-07-15 06:21 UTC, itrich approved these changes

2022-07-15 06:24 UTC, itrich commented
All lights are green now. Ready to be merged :rocket:

2022-07-15 17:03 UTC, merged