Add airgapped scs blogpost
SovereignCloudStack/website pull request #555
Opened 2023-02-24 06:27 UTC by tibeer

This is the blog post for airgapped SCS installations.
Watch out, the release date hasn't been selected yet.

Signed-off-by: Tim Beermann <beermann@osism.tech>

2023-02-24 07:21 UTC, itrich commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +![architecture](/assets/images/blog/airgap-architecture.png)
```suggestion
{% asset '/assets/images/blog/airgap-architecture.png' class="figure-img w-100" %}
```

We're using an asset pipeline to optimize rich media within our website. Thus the usual Markdown image tag won't work here. Feel free to accept my suggestion.

2023-02-24 07:26 UTC, itrich commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +image: "default-card.jpg"
In my personal opinion, the blog post will stand out more by using an individual share pic. What do you think about using something like: https://www.pexels.com/photo/antelope-canyon-in-arizona-2984868/?

2023-02-24 07:36 UTC, tibeer commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +image: "default-card.jpg"
Done.

2023-02-24 07:39 UTC, itrich commented
Thank you for accepting the proposed changes! I just pushed your branch to `staging` and triggered a rebuild of the staging site. It will be live within the next 10 minutes: https://sovereigncloudstack.github.io/website/tech/2023/02/24/airgapped-scs/

2023-02-24 08:28 UTC, itrich commented
This looks good to me from a technical standpoint. :+1: I'll let @fkr have a look at the content.

2023-03-03 12:58 UTC, fkr commented
Since we just had the blogpost from @ppkuschy I would suggest that we cover the Hackathon and after that we publish the air gapped post, sounds good to you @itrich?

2023-03-03 13:00 UTC, itrich commented
Sounds fine to me! :+1:

2023-03-13 08:44 UTC, itrich commented
@tibeer @fkr Would you agree that today is a good day to release this blog post?

2023-03-13 08:52 UTC, fkr commented
> @tibeer @fkr Would you agree that today is a good day to release this blog post?

I'll submit a few minor nits I found while reading through it. I'll do that until 1400 CET today.

2023-03-13 11:15 UTC, fkr commented
@tibeer I just pushed a few commits on top of the branch. These are mainly tyops, but a couple (imho very minor) rewordings. Please check and see wether you're fine with those.

2023-03-13 11:15 UTC, fkr approved these changes

2023-03-15 15:58 UTC, tibeer commented
@maxwolfs Unfortunately the "old" software stack required image integrations in this style:

```md
<figure class="figure mx-auto d-block" style="width:50%">
  <a href="{% asset "blog/airgap-architecture.png" @path %}">
    {% asset 'blog/airgap-architecture.png' class="figure-img w-100" %}
  </a>
</figure>
```

There seems to be some magic to obfuscate assets paths so they cannot be crawled easily. I don't know how you would like to structure things in docusaurus, but a simple 

```md
![airga-architecture](blog/airgap-architecture.png)
```

should do the trick.

2023-03-15 16:50 UTC, tibeer commented
@fkr @itrich blog post has been updated.

2023-03-16 13:38 UTC, frosty-geek commented
@maxwolfs @tibeer do we need to adjust the date of the files, or should this be merged as it is right now?

2023-03-22 15:06 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +Table of content:
```suggestion
Table of contents:
```

2023-03-22 15:08 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +The main reason for having an air gapped is of course based on customer requirements: Allowing industrial partners to host SCS as
```suggestion
The main reason for having an air gapped installation method is of course based on customer requirements: Allowing industrial partners to host SCS as
```

2023-03-22 15:14 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +    Starting with more or less the most complex component. Wormhole is a completly new software that is able to mirror
```suggestion
    Starting with more or less the most complex component: Wormhole is a completly new software that is able to mirror
```

2023-03-22 15:15 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +    also mirror other stuff like pypi packages, etc. Eventually we decided that pulp will not be the solution for us because: It
```suggestion
    also mirror other stuff like pypi packages, etc. Eventually we decided that pulp will not be the solution for us because of a variety of reasons: It
```

2023-03-22 15:17 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +    and even debugging the galaxy api. By the way: this might be the reason, why ansible itself want's to migrate to pulp. The
```suggestion
    the mirror software for the ansible-galaxy. It might not be pretty, but it does the job. However it did require reverse-engineering
    and even debugging the galaxy api. By the way: this might be the reason, why ansible itself want's to migrate to pulp. The
```

2023-03-22 15:18 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +    implementations evailable, all good enough to just use them. It's been battle proven as a reliable deb package mirror
```suggestion
    implementations available, all good enough to just use them. It's been battle proven as a reliable deb package mirror
```

2023-03-22 15:20 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +    implementations evailable, all good enough to just use them. It's been battle proven as a reliable deb package mirror
Regarding: "Battle proven" - I'd like to avoid terminology / wording that refers to combat or has a military background.

2023-03-22 15:20 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +    software. Aptly provides some sort of API functionality, but not everything we need. For the moment, twe decided that this is
```suggestion
    software. Aptly provides some sort of API functionality, but not everything we need. For the moment, we decided that this is
```

2023-03-22 15:20 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +    good enough, even if it involves some manual steps. In the current version, aplty is not used in the testbed as this is under
```suggestion
    good enough, even if it involves some manual steps. In the current version, aptly is not used in the testbed as this is under
```

2023-03-22 15:22 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +There is still one big problem: They all require an internet connection. But it's only these services, that require them. And the
```suggestion
There is still one big problem: They all require an internet connection. But it's only these services, that require them. The
```

2023-03-22 15:24 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +need to do on your own. We aim to prepare more information on this in the next featureset for air gapped installations.
```suggestion
There is still one big problem: They all require an internet connection, but only these services require the connection. Their
datastores can be prefilled and "manually migrated" to the air gapped installation. This however is something you
still need to do on your own. We aim to prepare more information on this in the next featureset for air gapped installations.
```

2023-03-22 15:26 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +deals also with container images. We use it for our own build containers, therefore we'll split container images into just "pure"
```suggestion
deals with container images. We use it for our own build containers, therefore we'll split container images into just "pure"
```

2023-03-22 15:27 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +ansible galaxy. That beeing said, it fakes some values in the API reposonses (like IDs or timestamps). It would just make no
```suggestion
ansible galaxy. That beeing said, it fakes some values in the API responses (like IDs or timestamps). It would just make no
```

2023-03-22 15:30 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +installation from the internet. This way, we will have finally a full air gap installation.
```suggestion
installation from the internet. This way, we will have a full air gap installation finally.
```

2023-03-22 15:32 UTC, fkr requested changes
Went over it. Left a few suggestions. These are (except a few) typos and grammar fixes.

2023-03-24 10:29 UTC, tibeer commented
@fkr reworked. Let's wait for the pipeline to finish.

2023-03-24 22:00 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +    also mirror other stuff like pypi packages, etc. Eventually we decided that pulp will not be the solution for us due of a variety of reasons: It
```suggestion
    also mirror other stuff like pypi packages, etc. Eventually we decided that pulp will not be the solution for us due to a variety of reasons: It
```

2023-03-24 22:01 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +    the mirror software for the ansible-galaxy. It might not be pretty, but it does the job. However it did required
```suggestion
    the mirror software for the ansible-galaxy. It might not be pretty, but it does the job. However it did require
```

2023-03-24 22:02 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +    reverse-engineering and even debugging the galaxy api. By the way: this might be the reason, why ansible itself want's to
```suggestion
    reverse-engineering and even debugging the galaxy api. By the way: this might be the reason, why ansible itself wants to
```

2023-03-24 22:16 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +[__wormhole__](github.com/osism/python-ansible-wormhole) can be used by you to mirror collections and roles from the official
```suggestion
[__Wormhole__](github.com/osism/python-ansible-wormhole) can be used by you to mirror collections and roles from the official
```

2023-03-24 22:17 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +ansible galaxy. That beeing said, it fakes some values in the API responses (like IDs or timestamps). It would just make no
```suggestion
ansible galaxy. That being said, it fakes some values in the API responses (like IDs or timestamps). It would just make no
```

2023-03-24 22:18 UTC, fkr commented on _i18n/en/_posts/blog/2023-02-24-airgapped-scs.md
> +[__banderctl__](github.com/osism/python-banderctl) creates an API endpoint in front of the bandersnatch clients config.
```suggestion
[__Banderctl__](github.com/osism/python-banderctl) creates an API endpoint in front of the bandersnatch clients config.
```

2023-03-24 22:20 UTC, fkr approved these changes
Made a few minor grammar fixes directly. LGTM.

2023-03-28 18:49 UTC, itrich commented
Did you already agree on a publication date? Is this ready to be deployed?
![image](https://i.giphy.com/media/DvMHwFYLVHlZe/giphy.webp)

2023-03-28 18:53 UTC, fkr commented
from my perspective this is ready to be published.

2023-04-12 06:58 UTC, merged