Add sport event blog post
SovereignCloudStack/website pull request #693
Opened 2023-07-05 14:00 UTC by FriederikeZelke

2023-07-05 14:54 UTC, berendt commented
Filename should be ``2023-07-05Sportveranstaltung.md``.

2023-07-05 14:56 UTC, berendt commented
Is there already an idea how big the individual teams are or will that only be decided when all the registrations are through?

2023-07-06 07:16 UTC, FriederikeZelke commented
We plan teams with 3-4 members. We decide when all registrations are there.

2023-07-06 11:47 UTC, maxwolfs requested changes
I found some things, otherwise 👍

2023-07-06 11:47 UTC, maxwolfs commented on _i18n/de/_posts/blog/2023-07-05Sortveranstaltung.md
> +Die Veranstaltung ist eine Sponsoren-/Spendenveranstaltung. Und es gibt mehrere Möglichkeiten zu sponsern:
```suggestion
Die Veranstaltung ist eine Sponsoren-/Spendenveranstaltung. Es gibt mehrere Möglichkeiten zu sponsern:
```

2023-07-06 11:47 UTC, maxwolfs commented on _i18n/de/_posts/blog/2023-07-05Sortveranstaltung.md
> +* Sponsoren zahlen einen Betrag, den er selbst festlegt, für alle Sportarten und Teilnehmer für jeweils (x):
```suggestion
* Sponsoren zahlen einen Betrag, den sie selbst festlegen, für alle Sportarten und Teilnehmer für jeweils (x):
```

2023-07-06 11:47 UTC, maxwolfs commented on _i18n/de/_posts/blog/2023-07-05Sortveranstaltung.md
> +{% asset 'blog/run.jpg' vips:format='.webp' style="width:100%; max-height: 350px; object-fit: cover;" %}
Does this work? Within this PR is no committed `run.jpg`

2023-07-06 11:52 UTC, FriederikeZelke commented on _i18n/de/_posts/blog/2023-07-05Sortveranstaltung.md
> +{% asset 'blog/run.jpg' vips:format='.webp' style="width:100%; max-height: 350px; object-fit: cover;" %}
What do you mean?

2023-07-06 14:39 UTC, FriederikeZelke reviewed
LGTM

2023-07-06 14:40 UTC, maxwolfs approved these changes

2023-07-06 14:40 UTC, merged