Blog post on OpenStack CLI and Device Authz Grant with PKCE
SovereignCloudStack/website pull request #728
Opened 2023-09-05 16:50 UTC by reqa

Linking to the location where the result of https://github.com/SovereignCloudStack/docs/pull/72 we be deployed, but that is not yet published.

2023-09-05 17:18 UTC, reqa commented
I've also added a section to explain the Horizon logout patch (https://github.com/SovereignCloudStack/issues/issues/347)

2023-09-06 09:06 UTC, JuanPTM reviewed
typos

2023-09-06 09:06 UTC, JuanPTM commented on _i18n/en/_posts/blog/2023-09-05-progress-openstack-cli-with-federation.md
> +did not get terminated and so the OpenID Connect token was stil valid. After some expermentation and research
```suggestion
did not get terminated and so the OpenID Connect token was still valid. After some experimentation and research
```

2023-09-20 06:42 UTC, garloff requested changes
At least the typo should be addressed.

2023-09-20 06:42 UTC, garloff commented on _i18n/en/_posts/blog/2023-09-05-progress-openstack-cli-with-federation.md
> +tje SCS hackathon in Cologne](https://scs.community/2023/01/05/sig-iam-openstack-cli-with-federation/), the IAM part of
```suggestion
the SCS hackathon in Cologne](https://scs.community/2023/01/05/sig-iam-openstack-cli-with-federation/), the IAM part of
```

2023-09-20 06:42 UTC, garloff commented on _i18n/en/_posts/blog/2023-09-05-progress-openstack-cli-with-federation.md
> +Arvid Requate (Member SCS "Operations and IAM" Team)
Literally, the "Operations and IAM" Team does not exist in this form ... since we have split the teams earlier this year.
If you quickly glance through our blog articles, we have not finished our blog articles with wishes from the author thus far. Maybe you wanted to do it on purpose, adding a more personal note here, and that's fine. If it was less on purpose and you were in mail writing mode when doing the last lines, maybe you scratch it?

2023-10-18 21:07 UTC, garloff approved these changes

2023-10-18 22:45 UTC, merged