feat/add blog post for status page technical preview release
SovereignCloudStack/website pull request #904
Opened 2024-04-18 09:14 UTC by snkaupe

Adds a blog post to announce the release of the status page technical preview.

2024-04-18 09:15 UTC, snkaupe commented
@joshuai96 I think we would want to add a link to our deployment repo for the status page. Is that done yet? Do you have suggestions for that sentence or paragraph?

2024-04-18 09:53 UTC, fkr commented on _i18n/en/_posts/blog/2024-04-18-status-page-tech-preview-release.md
> +Now matter how thorough your preparation and processes, services experiencing limited capabilities and straight-out outages *will* be part your business of being a cloud provider.
```suggestion
No matter how thorough your preparation and processes, services experiencing limited capabilities and straight-out outages *will* be part your business of being a cloud provider.
```

2024-04-18 09:54 UTC, fkr commented on _i18n/en/_posts/blog/2024-04-18-status-page-tech-preview-release.md
> +## The SCS Status Page is now available as a Technical Preview
```suggestion
## The SCS Status Page is available as a Technical Preview now
```

2024-04-18 09:56 UTC, fkr commented on _i18n/en/_posts/blog/2024-04-18-status-page-tech-preview-release.md
> +If you've ever seen a status page before, this page design will surely be immediately familiar to you. We have, however, implemented for our technical preview a few things not commonly seen in the st
```suggestion
If you've ever seen a status page before, the page design will surely be familiar to you immediately. However for our technical preview we've implemented a few things not commonly seen in the status pages we've encountered in our research.
```

2024-04-18 17:13 UTC, fkr commented on _i18n/en/_posts/blog/2024-04-18-status-page-tech-preview-release.md
> +You can find the Git repository of the status page [on GitHub](https://github.com/SovereignCloudStack/status-page-web). The README file includes instructions on how to construct a container image fro
```suggestion
You can find the Git repository of the status page [on GitHub](https://github.com/SovereignCloudStack/status-page-web). The [README](https://github.com/SovereignCloudStack/status-page-web/blob/main/README.md) file includes instructions on how to construct a container image from the sources and how to configure the status page according to your needs/status API server setup. You have no status API server yet? Not a problem—the status page repo comes with some example data included and you can set a flag to make the status page use that, allowing you to try out the page on its own.
```

2024-04-18 17:27 UTC, fkr commented on _i18n/en/_posts/blog/2024-04-18-status-page-tech-preview-release.md
> +For the moment (and our first complete release), the status page is a tool to purely view the status of your SCS environment. We have, however, a whole mountain of plans and ideas to implement in the
I would likely rephrase it a bit, since from the sentence '[...]the status page is a tool to purely view the status of your SCS environment.[...]" one could get the impression the status page is displaying live status and is somewhat hooked into the observability.

2024-04-18 18:19 UTC, fkr requested changes
Please look at this one paragraph / sentence I marked.

2024-04-19 09:15 UTC, snkaupe commented on _i18n/en/_posts/blog/2024-04-18-status-page-tech-preview-release.md
> +For the moment (and our first complete release), the status page is a tool to purely view the status of your SCS environment. We have, however, a whole mountain of plans and ideas to implement in the
This sentence has been rephrased. Is this better:

```
For the moment (and our first complete release), the status page is limited to just displaying the incident data of your status API server.
```

2024-04-24 06:39 UTC, fkr commented on _i18n/en/_posts/blog/2024-04-18-status-page-tech-preview-release.md
> +For the moment (and our first complete release), the status page is a tool to purely view the status of your SCS environment. We have, however, a whole mountain of plans and ideas to implement in the
I think, you misunderstood me. 
What I meant: the status page is not intended to report live status based on an observability source but intended to report status based on what is fed into it. This is not a limitation of the first release but simply the scope of the overall project. It does not 'report the status of the SCS environment' it reports the status of whatever is fed into it - this can be status of a SCS environment if that is what is fed into it. I'll submit a suggestion.

2024-04-24 06:41 UTC, fkr commented on _i18n/en/_posts/blog/2024-04-18-status-page-tech-preview-release.md
> +For the moment (and our first complete release), the status page is limited to just displaying the incident data of your status API server. We have, however, a whole mountain of plans and ideas to im
```suggestion
For the moment, and the scope of the first complete release, the status page frontend displays the incident data present in your status API server. We have a whole mountain of plans and ideas to implement in the future, chief amongst them the ability to create and update incidents and impacts for authenticated users, turning the status page into *the* tool to interact with the status API server. Additionally, we plan to extend the API specification, API server and frontend to schedule and display pre-planned maintenance sessions, allowing you to inform your users of expected outages well beforehand.
```

2024-04-24 08:19 UTC, snkaupe commented
Is this failure of the build a known problem? Every push to this PR seems to have run into this problem so far. This is apparently the cause:

```
Liquid Exception: couldn't find file '' in `_pages/blog.md'
```

The strange thing is that I did not touch this file. I've checked all files I modified for empty or missing filenames and haven't found anything so far.

2024-04-30 04:55 UTC, fkr commented
@snkaupe I fixed the problem, the symlink from de was dangling. Site is built up on staging: https://staging.scs.community/website/tech/2024/04/30/status-page-tech-preview-release/

I bumped the date to today, so if everything is OK for you, you can hit merge ;)

2024-04-30 06:30 UTC, snkaupe commented
Can't hit merge because your old review is still marked as "changes requested." Can you give me a quick new review with your approval?

2024-04-30 06:56 UTC, fkr approved these changes

2024-04-30 06:56 UTC, merged