Add blog post about local storage in cinder
SovereignCloudStack/website pull request #970
Opened 2024-06-27 09:03 UTC by janhorstmann

2024-06-27 09:04 UTC, janhorstmann commented
I was not able to get the local developement server running, so I have no idea if this actually looks like it is intended to.

2024-06-27 20:29 UTC, fkr commented
My suggestion would be to wait with publishing until after next weeks IaaS call, so that we could incorporate feedback from that discussion.

2024-06-28 07:25 UTC, janhorstmann commented
> My suggestion would be to wait with publishing until after next weeks IaaS call, so that we could incorporate feedback from that discussion.

I would also favor this approach

2024-07-09 12:26 UTC, fkr commented on _i18n/en/_posts/blog/2024-06-24-local-block-storage-via-dm-clone.md
> +title: "Proposal for a mechanism to provide node local storage in the OpenStack block storage service"
```suggestion
title: "Mechanism to provide node local storage in the OpenStack block storage service"
```

2024-07-09 12:31 UTC, fkr commented on _i18n/en/_posts/blog/2024-06-24-local-block-storage-via-dm-clone.md
> +The dm-clone target however lacks a means to specify device offsets. A feature needed to construct complex targets spanning multiple devices as the device-mapper's `linear` target offers and is most
```suggestion
The dm-clone target, however, lacks a means to specify device offsets. A feature needed to construct complex targets spanning multiple devices as the device-mapper's `linear` target offers and is most prominently used by the `lvm2` project. Therefore, in order to provide the most flexibility, it is proposed to use the `dm-clone` target stacked on top of device-mapper targets provided by `lvm2`. This implies, that after migration, a linear target will be stacked on top of the linear `lvm2` target.
```

2024-07-09 12:35 UTC, fkr commented on _i18n/en/_posts/blog/2024-06-24-local-block-storage-via-dm-clone.md
> +Naturally for a given risk of failure of a single node, the risk is doubled during the time frame of data migration between two nodes. Additionally network partitions or failure may occur, thus incre
```suggestion
Naturally for a given risk of failure of a single node, the risk is doubled during the time frame of data migration between two nodes. Additionally network partitions or failure may occur, thus increasing the risk further. The overall risk may be reduced by reducing the time frame of migration through increased network bandwidth.
```

2024-07-09 12:54 UTC, fkr commented on _i18n/en/_posts/blog/2024-06-24-local-block-storage-via-dm-clone.md
> +In case of the source being unreachable either by node or network failure or partition, data may not be read leading to read IO errors on the destination node, which will be further handled by the fi
The first part of the sentence is weird:

"In case of the source being unreachable either by node or network failure or partition[....]"

2024-07-09 12:57 UTC, fkr commented on _i18n/en/_posts/blog/2024-06-24-local-block-storage-via-dm-clone.md
> +  For the sppecial case that it is the volume-service holding the volume a connector object of type `local` is directly returned and the volume may be attached.
```suggestion
  For the special case that it is the volume-service holding the volume a connector object of type `local` is directly returned and the volume may be attached.
```

2024-07-09 13:13 UTC, fkr commented on _i18n/en/_posts/blog/2024-06-24-local-block-storage-via-dm-clone.md
> +  <a href="{% asset "blog/local-block-storage-via-dm-clone/volume-states-diagram.svg" @path %}">
```suggestion
  <a href="{% asset "blog/local-block-storage-via-dm-clone-volume-states-diagram.svg" @path %}">
```

2024-07-09 13:14 UTC, fkr requested changes
Very good blogpost, I like it a lot. There are a few suggestions and one correction to a path that need to be done.

2024-07-09 13:15 UTC, fkr commented
@janhorstmann you can view the rendered version here: https://sovereigncloudstack.github.io/website/2024/06/24/local-block-storage-via-dm-clone/

Be sure to fix the path to the .svg as in my review. Furthermore please update the date of the blogpost to now.

2024-07-10 10:06 UTC, janhorstmann commented on _i18n/en/_posts/blog/2024-06-24-local-block-storage-via-dm-clone.md
> +title: "Proposal for a mechanism to provide node local storage in the OpenStack block storage service"
yes, probably a better title

2024-07-10 10:06 UTC, janhorstmann commented on _i18n/en/_posts/blog/2024-06-24-local-block-storage-via-dm-clone.md
> +Naturally for a given risk of failure of a single node, the risk is doubled during the time frame of data migration between two nodes. Additionally network partitions or failure may occur, thus incre
fixed

2024-07-10 10:08 UTC, janhorstmann commented on _i18n/en/_posts/blog/2024-06-24-local-block-storage-via-dm-clone.md
> +In case of the source being unreachable either by node or network failure or partition, data may not be read leading to read IO errors on the destination node, which will be further handled by the fi
I wanted to mention partitions here, but I agree that it is clumsy. I've deleted the "partitions" part now as they can also be counted as general network failures

2024-07-10 10:08 UTC, janhorstmann commented on _i18n/en/_posts/blog/2024-06-24-local-block-storage-via-dm-clone.md
> +* When `initialize_connection` is called for a `reserved` volume the IP address in the provided connector obect needs to be resolved to a host running the volume-service with this driver as backend.
fixed

2024-07-10 10:08 UTC, janhorstmann commented on _i18n/en/_posts/blog/2024-06-24-local-block-storage-via-dm-clone.md
> +  For the sppecial case that it is the volume-service holding the volume a connector object of type `local` is directly returned and the volume may be attached.
fixed

2024-07-10 10:43 UTC, janhorstmann commented on _i18n/en/_posts/blog/2024-06-24-local-block-storage-via-dm-clone.md
> +  <a href="{% asset "blog/local-block-storage-via-dm-clone/volume-states-diagram.svg" @path %}">
fixed

2024-07-11 09:45 UTC, fkr commented on _members/jhorstmann.md
> +author_slug: janhorstmann
```suggestion
author_slug: jhorstmann
```

2024-07-11 09:46 UTC, fkr requested changes
please fix the author slug, that will fix the empty box :)

2024-07-12 06:07 UTC, janhorstmann commented on _members/jhorstmann.md
> +author_slug: janhorstmann
Thanks for spotting that

2024-07-12 06:09 UTC, janhorstmann commented
> please fix the author slug, that will fix the empty box :)

fixed. I have also updated the date

2024-07-12 06:15 UTC, fkr approved these changes

2024-07-12 06:15 UTC, merged